name: Deploy website

on: 
  pull_request:
    branches:
     - main

permissions:
  pull-requests: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Create _redirects file
        run: echo "/healthcare/*    /index.html   200" > build/_redirects

      - name: Install Netlify CLI
        run: npm install netlify-cli@17.10.1 -g

      - name: Deploy to Netlify
        id: netlify_deploy
        run: |
          netlify deploy \
            --dir build \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} \
            --json \
            --prod \
            --alias healthcare \
            > deploy_output.json
            
      - name: Generate URL Preview
        id: url_preview
        if: ${{ env.BRANCH_NAME != 'main' }}
        run: |
          NETLIFY_PREVIEW_URL=$(jq -r '.deploy_url' deploy_output.json)
          echo "NETLIFY_PREVIEW_URL=$NETLIFY_PREVIEW_URL" >> "$GITHUB_ENV"
          
      - name: Comment URL Preview on PR
        if: ${{ env.BRANCH_NAME != 'main' }}
        uses: actions/github-script@v7
        with:
          script: |
            const previewUrl = process.env.NETLIFY_PREVIEW_URL;
            const issue_number = context.issue.number; // Directly get the PR number
            await github.rest.issues.createComment({
              issue_number: issue_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Preview URL: ${previewUrl}`
            });
