name: ESLint Check

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write

jobs: 
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint:strict
        continue-on-error: true
        id: eslint

      - name: Check ESLint result
        if: steps.eslint.outcome == 'failure'
        run: |
          echo "ESLint found issues. Failing the workflow."
          exit 1
          
      - name: Block PR if ESLint fails
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              event: 'REQUEST_CHANGES',
              body: 'ESLint check failed. Please fix all linting issues (including warnings) before merging.'
            })

  deploy-preview:
    needs: lint
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: install all the Dependencies
        run: npm ci

      - name: build project from react files
        run: npm run build

      - name: create _redirects file
        run: echo "/healthcare/*    /index.html   200" > build/_redirects

      - name: install Netlify CLI
        run: npm install netlify-cli@17.10.1 -g

      - name: deploy to Netlify Preview page consist of userPR
        id: netlify_deploy
        run: |
          netlify deploy \
            --dir build \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} \
            --json \
            --alias "healthcare-${{ github.actor }}" \
            > deploy_output.json

      - name: Generate URL Preview
        id: url_preview
        run: |
          NETLIFY_PREVIEW_URL=$(jq -r '.deploy_url' deploy_output.json)
          echo "NETLIFY_PREVIEW_URL=$NETLIFY_PREVIEW_URL" >> "$GITHUB_ENV"
          
      - name: Comment URL Preview on PR
        uses: actions/github-script@v7
        with:
          script: |
            const previewUrl = process.env.NETLIFY_PREVIEW_URL;
            const issue_number = context.issue.number; // Directly get the PR number
            const username = context.actor; // Get the username of the person who raised the PR
            if (previewUrl) {
              await github.rest.issues.createComment({
                issue_number: issue_number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `Preview URL for ${username}: ${previewUrl}`
              });
            } else {
              await github.rest.issues.createComment({
                issue_number: issue_number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `Deployment failed or no preview URL available for ${username}.`
              });
            }
